name: Build

on:
  push:
    paths:
      - .github/workflows/build.yml
      - .dockerignore
      - Dockerfile.build
      - uv.lock
      - pyproject.toml
      - '**.py'

jobs:
  test:
    uses: winstxnhdw/actions/.github/workflows/uv.yml@main

  build:
    if: github.ref == 'refs/heads/main'
    uses: winstxnhdw/actions/.github/workflows/docker-push.yml@main
    with:
      file: Dockerfile.build
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: write

  restart:
    if: github.ref == 'refs/heads/main'
    needs: [test, build]
    uses: winstxnhdw/actions/.github/workflows/spaces-restart.yml@main
    secrets:
      token: ${{ secrets.HF_TOKEN }}
